spring.application.name=EXE_Project
# Connection URL for SQL Server using the Microsoft JDBC driver
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=exe_project;encrypt=false;

# Database username and password
spring.datasource.username=sa
spring.datasource.password=123

# Use the Microsoft SQL Server JDBC driver
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Hibernate settings suitable for Microsoft SQL Server
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServer2012Dialect
spring.jpa.properties.hibernate.hbm2ddl.auto=none
spring.jpa.properties.hibernate.show_sql=true

# Physical naming strategy
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# Đường dẫn để Java lưu file vào ổ cứng
file.upload-dir=D:/SpringBoot/EXE/EXE_DataUploads/

# Đường dẫn để Spring Boot nhận diện (Resource Handler)
file.resource-path=file:///D:/SpringBoot/EXE/EXE_DataUploads/